In [1]:
import torch

In [2]:
tenso_1 = torch.rand(size=(7,7))
tenso_2 = torch.rand(size=(1,7))

In [3]:
tenso_1@tenso_2.T

tensor([[1.8054],
        [1.8509],
        [1.2344],
        [1.7684],
        [1.0812],
        [2.2796],
        [1.9049]])

In [4]:
see_d = 43
 
torch.manual_seed(see_d)


In [5]:
device='cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [6]:
tenso_1.to(device)
tenso_2.to(device)

tensor([[0.0215, 0.9972, 0.7134, 0.5148, 0.1393, 0.5802, 0.1400]],
       device='cuda:0')

In [7]:
ere = tenso_1@tenso_2.T
ere

tensor([[1.8054],
        [1.8509],
        [1.2344],
        [1.7684],
        [1.0812],
        [2.2796],
        [1.9049]])

In [8]:
torch.max(ere), torch.min(ere)

(tensor(2.2796), tensor(1.0812))

In [9]:
torch.argmax(ere), torch.argmin(ere)

(tensor(5), tensor(4))

In [10]:
piie = torch.rand(size=(1,1,4,4))
print(piie.ndim, piie.shape)
piie1 = piie.squeeze()
piie1.ndim


4 torch.Size([1, 1, 4, 4])


2