In [1]:
import torch
torch.__version__

'2.0.0'

In [2]:
scalar = torch.tensor(7)
scalar,scalar.ndim

(tensor(7), 0)

In [3]:
scalar.item()

7

In [4]:
vector = torch.tensor([22,23])
vector, vector.ndim, vector.shape,vector[0],vector[1]

(tensor([22, 23]), 1, torch.Size([2]), tensor(22), tensor(23))

In [5]:
matrix = torch.tensor([[2,9],[5,6],[8,9]])
matrix, matrix.ndim, matrix.shape, 

(tensor([[2, 9],
         [5, 6],
         [8, 9]]),
 2,
 torch.Size([3, 2]))

In [6]:
Tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,1],[1,1,3],[1,2,3]]])
Tensor, Tensor.ndim, Tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 1],
          [1, 1, 3],
          [1, 2, 3]]]),
 3,
 torch.Size([3, 3, 3]))

In [7]:
##size---->[1,3,3]
set_1 = torch.tensor([[[1,2,3],[1,2,3],[1,2,3]]])
##size---->[2,3,3]
set_2 = torch.tensor([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])
##size---->[3,3,3]
set_3 = torch.tensor([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])
set_1,set_1.shape, set_2,set_2.shape, set_3, set_3.shape

(tensor([[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]]),
 torch.Size([1, 3, 3]),
 tensor([[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],
 
         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]]),
 torch.Size([2, 3, 3]),
 tensor([[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],
 
         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],
 
         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]]),
 torch.Size([3, 3, 3]))

In [8]:
set_1.ndim, set_2.ndim, set_3.ndim

(3, 3, 3)

In [9]:
random_tensor = torch.rand(size = (3,4))
random_tensor, random_tensor.dtype, random_tensor.ndim

(tensor([[0.2947, 0.7136, 0.0742, 0.9200],
         [0.4094, 0.1993, 0.7055, 0.2232],
         [0.2439, 0.3809, 0.7897, 0.0501]]),
 torch.float32,
 2)

In [10]:
random_image_tensor = torch.rand(size=(3,128,128))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 128, 128]), 3)

In [11]:
random_image_tensor

tensor([[[0.3084, 0.7495, 0.8845,  ..., 0.9912, 0.4678, 0.3701],
         [0.3141, 0.8006, 0.3452,  ..., 0.1778, 0.3695, 0.0931],
         [0.3235, 0.4687, 0.6950,  ..., 0.5291, 0.0258, 0.1710],
         ...,
         [0.7815, 0.1380, 0.5467,  ..., 0.2115, 0.3924, 0.0215],
         [0.5181, 0.2056, 0.8763,  ..., 0.5874, 0.0831, 0.6931],
         [0.6403, 0.1061, 0.4215,  ..., 0.8358, 0.7619, 0.6048]],

        [[0.8596, 0.1501, 0.0291,  ..., 0.5697, 0.0162, 0.4275],
         [0.6916, 0.8391, 0.4534,  ..., 0.9767, 0.8225, 0.3152],
         [0.1414, 0.2880, 0.5041,  ..., 0.1393, 0.7468, 0.5321],
         ...,
         [0.8964, 0.0845, 0.5769,  ..., 0.8649, 0.1831, 0.9744],
         [0.8299, 0.3306, 0.1132,  ..., 0.0144, 0.6713, 0.4185],
         [0.5220, 0.7933, 0.4992,  ..., 0.9985, 0.0234, 0.9228]],

        [[0.2227, 0.0295, 0.4591,  ..., 0.8320, 0.8918, 0.4314],
         [0.0865, 0.2489, 0.0300,  ..., 0.3526, 0.1684, 0.3942],
         [0.1974, 0.4542, 0.7415,  ..., 0.0987, 0.7107, 0.

In [12]:
##Zeros and Ones tensor
zeros = torch.zeros(size =(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [13]:
ones = torch.ones(size=(2,2))
ones, ones.shape, ones.ndim

(tensor([[1., 1.],
         [1., 1.]]),
 torch.Size([2, 2]),
 2)

In [14]:
# by default step size is 1
ek_se_dus = torch.arange(start = 2, end =31, step=2 )
ek_se_dus, ek_se_dus.shape, ek_se_dus.ndim

(tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]),
 torch.Size([15]),
 1)

In [15]:
## this one is interesting

fifteen_zeros = torch.zeros_like(input= ek_se_dus)

fifteen_ones = torch.ones_like(input=ek_se_dus)
fifteen_zeros,fifteen_ones

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [16]:
ur = torch.rand(size=(3,4))

In [17]:
#Its time to play around with Floating point numbers.
float_32_tensor = torch.tensor([3,4,5,6],dtype=torch.float32,device=None,requires_grad=False)
# float_32_tensor = torch.tensor(ur,dtype=None,device=None,requires_grad=False)

In [18]:
float_32_tensor, float_32_tensor.shape, float_32_tensor.ndim, float_32_tensor.dtype

(tensor([3., 4., 5., 6.]), torch.Size([4]), 1, torch.float32)

In [19]:
ur, ur.ndim,ur.shape,ur.dtype

(tensor([[0.7401, 0.5150, 0.8947, 0.0754],
         [0.4450, 0.8571, 0.6765, 0.2076],
         [0.9845, 0.4730, 0.5025, 0.1276]]),
 2,
 torch.Size([3, 4]),
 torch.float32)

In [20]:
##Manipulating Tensors i.e. Operations performed on Tensors
## +(addition),-(subtraction),*(multiplication),/(division),@(Matrix Multiplication)




In [21]:
tensor_a = torch.tensor([1,2,3])
print(tensor_a)
bb = tensor_a+10
# type(bb)
cc = tensor_a - 0.1
dd = tensor_a * 10
ee = tensor_a / 0.1
# ff = tensor_a 
print(bb,cc,dd,ee)
dd.dtype, ee.dtype

tensor([1, 2, 3])
tensor([11, 12, 13]) tensor([0.9000, 1.9000, 2.9000]) tensor([10, 20, 30]) tensor([10., 20., 30.])


(torch.int64, torch.float32)

In [22]:
torch.multiply(ee, 10)

tensor([100., 200., 300.])

In [23]:
ff = dd*dd
ff ## element wise multiplication

tensor([100, 400, 900])

In [24]:
##Lets look into matrix Multiplication
## torch.matmul
torch.matmul(dd,dd) ## element wise multiplication and addition


tensor(1400)

In [25]:
dd@dd

tensor(1400)

In [26]:
aa = torch.rand(size=(2,3), dtype = torch.float32)
print(aa)
gg = torch.tensor([[1,2],[3,4],[5,6]], dtype =torch.float32)
print(gg)
# aa@gg
torch.matmul(aa,gg)
## note @ or torch.matmul won't work in dtype = torch.float16 or lower
## unless you autocast your var in Cuda or make its dtype
## torch.float32
## And more importantly remember the matrix multiplication rule for dimension


tensor([[0.2108, 0.0864, 0.0348],
        [0.6531, 0.5063, 0.4016]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


tensor([[0.6440, 0.9760],
        [4.1799, 5.7409]])

In [27]:
## to make a transpose use tensor.T
# print(gg@gg)  or print(aa@aa) ## won't work
print(gg@aa)
print(aa@gg)
print(gg@gg.T)
print(aa@aa.T)

tensor([[1.5170, 1.0991, 0.8379],
        [3.2449, 2.2847, 1.7105],
        [4.9727, 3.4703, 2.5831]])
tensor([[0.6440, 0.9760],
        [4.1799, 5.7409]])
tensor([[ 5., 11., 17.],
        [11., 25., 39.],
        [17., 39., 61.]])
tensor([[0.0531, 0.1954],
        [0.1954, 0.8442]])


**Most commonly errors in DL are of Three Types:**
**Shape mismatch during matmul**
**Placement of Vars(one in GPU and other in CPU)**
**And their dtype**

**@ or torch.mm or torch.matmul They mean the Same**

In [28]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features = 2 , out_features=6)
x = torch.rand(size=(2,2))
print(x, type(x), x.dtype, x.shape, x.ndim)
output = linear(x)
output, output.shape

tensor([[0.2666, 0.6274],
        [0.2696, 0.4414]]) <class 'torch.Tensor'> torch.float32 torch.Size([2, 2]) 2


(tensor([[ 1.0348,  0.4592,  0.3892,  0.0690,  0.3858,  0.3514],
         [ 0.9272,  0.3378,  0.3622, -0.0094,  0.4842,  0.3286]],
        grad_fn=<AddmmBackward0>),
 torch.Size([2, 6]))

In [29]:
# Finding min max mean sum
x = torch.arange(0,100,10)

print(x,x.min(), x.max(), x.sum(), len(x))

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) tensor(0) tensor(90) tensor(450) 10


In [30]:
print(x.type(torch.float32).mean())

tensor(45.)


In [31]:
##Another way to do this issss....
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(0), tensor(90), tensor(45.), tensor(450))

In [32]:
##Now something to do with positional argument
tensorr = torch.rand(12,2)
tensorr

tensor([[0.2969, 0.8317],
        [0.1053, 0.2695],
        [0.3588, 0.1994],
        [0.5472, 0.0062],
        [0.9516, 0.0753],
        [0.8860, 0.5832],
        [0.3376, 0.8090],
        [0.5779, 0.9040],
        [0.5547, 0.3423],
        [0.6343, 0.3644],
        [0.7104, 0.9464],
        [0.7890, 0.2814]])

In [33]:
tensorr.argmax(), tensorr.argmin()

(tensor(8), tensor(7))

In [34]:
## to change tensor datatypes
tensor = torch.arange(10.,100.,10.)
print(tensor.dtype)
tensor_16 = tensor.type(torch.float16)
tensor_16.dtype

torch.float32


torch.float16

In [35]:
##Reshaping , Stacking, squeezing, unsqueezing
y = torch.arange(1.,8.)
y, y.shape, y.ndim

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]), 1)

In [36]:
## (torch.reshape() )reshape adds a dimension to the current dimension of the tensor
## in which it is applied
y_reshaped = y.reshape(1,7)
y_reshaped, y_reshaped.shape, y_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]), 2)

In [37]:
z = y.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [38]:
z[:,0] = 5
z,y

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [39]:
## dim=0 ====>> stacking on the top of each other
## dim=0 ====>> Rows wise stacking
## dim=1 ====>> taking transpose and then stacking column wise
## dim=0 > Row and dim=1 > Column

y_stacked = torch.stack([y,y,y,y], dim=1)
y_stacked, y_stacked.ndim, y_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.]]),
 2,
 torch.Size([7, 4]))

In [40]:
## Squeeze <> UnSqueeze
## Squeeze removes one dimesion at a time
## Unsqueeze adds an extra dimension
y_reshaped, y_reshaped.shape, y_reshaped.ndim

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]), 2)

In [41]:
y1 = y_reshaped.squeeze()
y1, y1.shape, y1.ndim

(tensor([5., 2., 3., 4., 5., 6., 7.]), torch.Size([7]), 1)

In [42]:
y2 = y1.unsqueeze(dim =0) # requires positional arg as to where to Row/col
y2, y2.shape, y2.ndim
# y2 == y_reshaped


(tensor([[5., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]), 2)

In [43]:
## Rearrange the order of Axes
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(0,1,2)
print(x_original.shape)
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([224, 224, 3])


In [44]:
##Indexing
x = torch.arange(1,10).reshape(1,3,3)
x
# try reshape(9), reshape(1,9), reshape(1,3,3)
x1 = x.reshape(9)
x2 = x.reshape(1,9)
x3 = x.reshape(1,3,3)
x1,x1.shape,x1.ndim,x2,x2.shape,x2.ndim,x3,x3.shape, x3.ndim
## did you see the connection !!

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.Size([9]),
 1,
 tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([1, 9]),
 2,
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [45]:
x[:,0], x[:,1,1], x[:,:,1],x[0,0,:]

(tensor([[1, 2, 3]]), tensor([5]), tensor([[2, 5, 8]]), tensor([1, 2, 3]))

In [46]:

import numpy as np

In [47]:
ara = np.arange(1.0,8.0)
ten = torch.from_numpy(ara)
ara, ten, ara+1, ten+1

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [48]:
arat = ten.numpy()
arat

array([1., 2., 3., 4., 5., 6., 7.])

In [49]:
!nvidia-smi

Sun Aug  6 12:25:57 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [50]:
torch.cuda.is_available()

True

In [51]:
device = "cuda" if torch.cuda.is_available() else "cpu"


In [52]:
device, torch.cuda.device_count()

('cuda', 1)

In [53]:
ten.to(device)

tensor([1., 2., 3., 4., 5., 6., 7.], device='cuda:0', dtype=torch.float64)

In [54]:
ten.cpu().numpy()

array([1., 2., 3., 4., 5., 6., 7.])

In [55]:
ten

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)